version: 2
updates:
  - package-ecosystem: "pip" # Set to 'pip' for Python projects
    directory: "/" # Path to the directory containing your 'requirements.txt' or 'Pipfile'
    schedule:
      interval: "monthly" # Frequency for Dependabot to check for updates
    open-pull-requests-limit: 5 # Optional: limit the number of open pull requests
