# File: .github/workflows/run_pytest.yml

# Name of the GitHub Actions workflow
name: Run Checks

# Trigger conditions: on push or pull requests to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  # First job: Running pytest
  pytest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Environment variables from GitHub Secrets
    env:
      GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
      GOOGLE_CREDENTIAL_DICT: ${{ secrets.GOOGLE_CREDENTIAL_DICT }}
      CODE_ENVIRONMENT: ${{ secrets.CODE_ENVIRONMENT }}
    
    # Steps to be run in this job
    steps:
      # Step 1: Checkout the code into the runner
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      # Step 4: Run pytest to execute tests
      - name: Run pytest
        run: pytest

  # Additional jobs can be added here, and can be set to depend on the 'pytest' job
  # by using the 'needs' field.
